fix: script

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -18,6 +18,10 @@ if [ -f "$PACKAGE_PATH" ]; then
         
         # Update only the version line in the file, preserving formatting
         sed -i -E "s/([ ]*\"version\": \")[0-9]+\.[0-9]+\.[0-9]+(\")$/\1$NEW_VERSION\2/" "$PACKAGE_PATH"
+    
+    else
+        echo "Error: version not found in package.json"
+        exit 1
     fi
     
     # Add the modified files to git
